name: Sync Docs to Global
on:
  push:
    branches: [main]
    paths: ["Documentation/**"]

jobs:
  sync-docs:
    uses: Varian-s-Unreal-Plugins/Documentation/.github/workflows/sync-plugin-docs.yml@main
    with:
      target_subfolder: "OmniToolbox"
    secrets:
      DOCS_PAT: ${{ secrets.DOCS_PAT }}
